services:
  - type: web
    name: laravel-backend
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear
      php artisan optimize
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          name: laravel-db
          type: postgres
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromService:
          name: laravel-db
          type: postgres
          property: database
      - key: DB_USERNAME
        fromService:
          name: laravel-db
          type: postgres
          property: user
      - key: DB_PASSWORD
        fromService:
          name: laravel-db
          type: postgres
          property: password

databases:
  - name: laravel-db
    plan: free
